"""Type stubs for the pyrei._pyrei C extension module."""

from collections.abc import Callable, Iterable
from typing import Any

__core_version__: str

class _Sentinel:
    """A terminal-state sentinel singleton (identity-tested)."""

    def __repr__(self) -> str: ...

FULL: _Sentinel
TIMEOUT: _Sentinel
CLOSED: _Sentinel
PEER_GONE: _Sentinel

def is_sentinel(x: Any) -> bool: ...
def abi_version() -> int: ...
def prune() -> list[str]: ...
def _tune_malloc() -> None: ...

class ReiError(Exception):
    """Base class for pyrei errors."""

class ShmError(ReiError):
    """Shared-memory setup/teardown failure."""

class StartupError(ReiError):
    """A peer or worker failed to attach within the startup timeout."""

class StoppedError(ReiError):
    """The pool is stopped or stopping."""

class SlotsExhaustedError(ReiError):
    """No free result slots for a submission."""

class SubmitTimeoutError(ReiError):
    """Submission timed out waiting for injection-ring space."""

class CancelledError(ReiError):
    """The task was cancelled before it ran."""

class TaskError(ReiError):
    """A task raised; carries the remote error envelope."""

    remote_type: str
    remote_traceback: str

class WorkerDiedError(ReiError):
    """The executing worker died while the task was in flight."""

    slot: int
    pid: int
    lost: list  # set by Pool.map on the worker-death path

class _Task:
    """A submitted-task handle."""

    @property
    def state(self) -> str: ...
    @property
    def pool(self) -> _Pool: ...
    def collect(self, timeout: float | None = None) -> Any: ...
    def cancel(self) -> bool: ...

class _Channel:
    """Low-level channel handle (use pyrei.Channel)."""

    @property
    def token(self) -> str: ...
    def ready_wait(self, timeout: float) -> bool: ...
    def ready_set(self) -> None: ...
    def send(self, x: Any) -> _Sentinel | None: ...
    def send_batch(self, xs: Any) -> int: ...
    def recv(self, timeout: float | None = None) -> Any: ...
    def recv_batch(
        self, n: int = 256, timeout: float | None = None
    ) -> Any: ...
    def close(self, timeout: float = 5.0) -> bool: ...
    def close_signal(self) -> None: ...
    def destroy(self) -> None: ...
    def alive(self) -> bool: ...
    def info(self) -> dict: ...

class _Pool:
    """Low-level pool handle (use pyrei.Pool)."""

    @property
    def token(self) -> str: ...
    def ready_wait(self, slots: list, timeout: float) -> bool: ...
    def submit(
        self, payload: tuple, timeout: float | None = None
    ) -> _Task: ...
    def submit_batch(
        self, payloads: list, timeout: float | None = None
    ) -> list: ...
    def collect_any(
        self, tasks: Iterable[_Task], timeout: float | None = None
    ) -> Any: ...
    def collect_all(
        self, tasks: Iterable[_Task], timeout: float | None = None
    ) -> Any: ...
    def retire(self, slot: int) -> None: ...
    def stop(self, timeout: float = 5.0) -> bool: ...
    def destroy(self) -> None: ...
    def status(self) -> dict: ...
    def dump(self) -> dict: ...
    def stats(self) -> dict: ...
    def set_trace(self, fn: Callable[[str, str], None] | None) -> None: ...
    def lame_duck(self) -> None: ...
    def leave(self) -> None: ...
    def run(self) -> int: ...
    def _signals(self) -> Any: ...
    def _help_once(self) -> bool: ...
    def _map_caps(self) -> tuple: ...
    def _submit_runner(
        self, payload: tuple, timeout: float | None = None
    ) -> _Task: ...

def _channel_new(
    capacity: int,
    slot_size: int,
    arena_size: int,
    spin: bool,
    drop: bytes,
) -> _Channel: ...
def _channel_attach(token: str) -> tuple: ...
def _pool_new(
    max_workers: int,
    max_submitters: int,
    injection_cap: int,
    per_worker_cap: int,
    result_slots: int,
    slot_size: int,
) -> _Pool: ...
def _pool_attach(token: str) -> _Pool: ...
def _pool_worker_join(token: str, slot: int) -> _Pool: ...
def _task_frame(fn: Any, args: tuple, kwargs: dict) -> tuple: ...
def _read_stream(stream: bytes) -> Any: ...

# Parallel-map support (src/map.c); capsules are opaque region handles.
def _map_probe_x(x: Any) -> tuple: ...
def _map_stage(*args: Any) -> tuple: ...
def _map_open(name: str) -> Any: ...
def _map_close(capsule: Any) -> None: ...
def _map_header(capsule: Any) -> dict: ...
def _map_desc(capsule: Any) -> bytes: ...
def _map_x_view(capsule: Any) -> Any: ...
def _map_next(capsule: Any, signals: Any, ordinal: int, gen: int) -> Any: ...
def _map_cancel_set(capsule: Any) -> None: ...
def _map_cancel_get(capsule: Any) -> bool: ...
def _map_reset(capsule: Any) -> int: ...
def _map_swap_x(capsule: Any, x: Any) -> None: ...
def _map_abandon(capsule: Any, k: int, gen: int) -> Any: ...
def _map_lost(capsule: Any, hists: list) -> list: ...
def _map_write(capsule: Any, lo: int, values: Any) -> None: ...
def _map_gather(capsule: Any) -> bytes: ...
def _map_gather_view(capsule: Any) -> Any: ...
