#!/usr/bin/env bash
# Vendors the librei core into src/vendor/librei/: the public header, the
# binding-author header (rei_ext.h — the package's own TUs compile against
# it, never internal.h), the internal header (the vendored core TUs still
# include it), and all core TUs, flattened. No substitutions — pyrei's
# namespace is rei's own, so the core vendors natively (see the ipc plan,
# Phase 2).
#
# Usage: tools/vendor-librei.sh [ref]
#   ref         tag, branch, or full commit SHA to vendor (default: the pin)
#   LIBREI_SRC  use a local librei checkout instead of cloning (must be at ref)
#   LIBREI_REPO override the upstream clone URL
#
# Vendored files are never edited by hand (see AGENTS.md): changes go
# upstream to librei and are pulled by re-running this script. Idempotent.
# The script greps its own output for stray sora/mori remnants and fails
# non-zero on any hit.

set -euo pipefail

PIN="a96807fe2425a1f08b8c9b2be3302c6cdf3a4fae"  # librei: Add REI_TYPE_INT64 wire tag
REF="${1:-$PIN}"
REPO="${LIBREI_REPO:-https://github.com/shikokuchuo/librei}"
DEST="$(cd "$(dirname "$0")/.." && pwd)/src/vendor/librei"

workdir=""
cleanup() { if [ -n "$workdir" ]; then rm -rf "$workdir"; fi; }
trap cleanup EXIT

if [ -n "${LIBREI_SRC:-}" ]; then
  src_root="$LIBREI_SRC"
else
  workdir="$(mktemp -d)"
  if printf '%s' "$REF" | grep -qE '^[0-9a-f]{40}$'; then
    # A commit SHA is not a ref: fetch it directly (GitHub serves reachable
    # SHAs) — clone --branch only takes branch/tag names.
    git init -q "$workdir/librei"
    git -C "$workdir/librei" remote add origin "$REPO"
    git -C "$workdir/librei" fetch -q --depth 1 origin "$REF"
    git -C "$workdir/librei" -c advice.detachedHead=false checkout -q FETCH_HEAD
  else
    git clone -q --depth 1 --branch "$REF" "$REPO" "$workdir/librei"
  fi
  src_root="$workdir/librei"
fi

commit="$(git -C "$src_root" rev-parse HEAD)"
commit_date="$(git -C "$src_root" log -1 --format=%cI HEAD)"
if [ -n "$(git -C "$src_root" status --porcelain -- src include)" ]; then
  commit="$commit-dirty"   # LIBREI_SRC with uncommitted changes
fi

# The directory is fully generated: clear stale files before repopulating.
mkdir -p "$DEST"
rm -f "$DEST"/*.c "$DEST"/*.h "$DEST"/VENDOR

cp "$src_root/include/rei.h" "$DEST/rei.h"
cp "$src_root/include/rei_ext.h" "$DEST/rei_ext.h"
cp "$src_root/src/internal.h" "$DEST/internal.h"
for f in "$src_root"/src/*.c; do
  cp "$f" "$DEST/"
done

# The gate: the core is language-agnostic — no binding-side remnants.
if grep -rnE 'sora|SORA|mori_|MORI_|MORH|MORS|MORL' "$DEST"; then
  echo "vendor-librei: FAIL — stray sora/mori remnants above" >&2
  exit 1
fi

{
  echo "Vendored librei core — generated by tools/vendor-librei.sh; do not edit."
  echo
  echo "upstream: $REPO"
  echo "ref: $REF"
  echo "commit: $commit"
  echo "commit-date: $commit_date"
  echo "license: MIT (same author) — see upstream LICENSE"
  echo
  (cd "$DEST" && shasum -a 256 *.c *.h)
} > "$DEST/VENDOR"

echo "vendored librei @ $REF ($commit) into $DEST"
