#!/usr/bin/env bash
# Vendors the libmizu core into src/vendor/libmizu/: the public header, the
# binding-author header (mizu_ext.h — the package's own TUs compile against
# it, never internal.h), the internal header (the vendored core TUs still
# include it), and all core TUs, flattened. No substitutions — pymizu's
# namespace is mizu's own, so the core vendors natively (see the ipc plan,
# Phase 2).
#
# Usage: tools/vendor-libmizu.sh [ref]
#   ref         tag, branch, or full commit SHA to vendor (default: the pin)
#   LIBMIZU_SRC  use a local libmizu checkout instead of cloning (must be at ref)
#   LIBMIZU_REPO override the upstream clone URL
#
# Vendored files are never edited by hand (see AGENTS.md): changes go
# upstream to libmizu and are pulled by re-running this script. Idempotent.
# The script greps its own output for stray sora/mori/rei remnants and fails
# non-zero on any hit.

set -euo pipefail

PIN="8c26849b3de0e97b894f7a039286f74f454cce51"  # libmizu: the task tag (Phase 4): normative format, task corpus fixtures
REF="${1:-$PIN}"
REPO="${LIBMIZU_REPO:-https://github.com/shikokuchuo/libmizu}"
DEST="$(cd "$(dirname "$0")/.." && pwd)/src/vendor/libmizu"

workdir=""
cleanup() { if [ -n "$workdir" ]; then rm -rf "$workdir"; fi; }
trap cleanup EXIT

if [ -n "${LIBMIZU_SRC:-}" ]; then
  src_root="$LIBMIZU_SRC"
else
  workdir="$(mktemp -d)"
  if printf '%s' "$REF" | grep -qE '^[0-9a-f]{40}$'; then
    # A commit SHA is not a ref: fetch it directly (GitHub serves reachable
    # SHAs) — clone --branch only takes branch/tag names.
    git init -q "$workdir/libmizu"
    git -C "$workdir/libmizu" remote add origin "$REPO"
    git -C "$workdir/libmizu" fetch -q --depth 1 origin "$REF"
    git -C "$workdir/libmizu" -c advice.detachedHead=false checkout -q FETCH_HEAD
  else
    git clone -q --depth 1 --branch "$REF" "$REPO" "$workdir/libmizu"
  fi
  src_root="$workdir/libmizu"
fi

commit="$(git -C "$src_root" rev-parse HEAD)"
commit_date="$(git -C "$src_root" log -1 --format=%cI HEAD)"
if [ -n "$(git -C "$src_root" status --porcelain -- src include)" ]; then
  commit="$commit-dirty"   # LIBMIZU_SRC with uncommitted changes
fi

# The directory is fully generated: clear stale files before repopulating.
mkdir -p "$DEST"
rm -f "$DEST"/*.c "$DEST"/*.h "$DEST"/VENDOR

cp "$src_root/include/mizu.h" "$DEST/mizu.h"
cp "$src_root/include/mizu_ext.h" "$DEST/mizu_ext.h"
cp "$src_root/src/internal.h" "$DEST/internal.h"
for f in "$src_root"/src/*.c; do
  cp "$f" "$DEST/"
done

# The golden interop corpus rides the same pin as the core: a spec change
# and its fixtures arrive in one re-vendor.
FIXDEST="$(cd "$(dirname "$0")/.." && pwd)/tests/interop-corpus"
mkdir -p "$FIXDEST"
cp "$src_root/tests/interop/cases.txt" "$FIXDEST/cases.txt"
cp "$src_root/tests/interop/corpus.txt" "$FIXDEST/corpus.txt"

# The gate: the core is language-agnostic — no binding-side remnants.
if grep -rnE 'sora|SORA|mori_|MORI_|MORH|MORS[^E]|MORL|rei_|REI_|\brei\b|0x524549' "$DEST"; then
  echo "vendor-libmizu: FAIL — stray sora/mori/rei remnants above" >&2
  exit 1
fi

{
  echo "Vendored libmizu core — generated by tools/vendor-libmizu.sh; do not edit."
  echo
  echo "upstream: $REPO"
  echo "ref: $REF"
  echo "commit: $commit"
  echo "commit-date: $commit_date"
  echo "license: MIT (same author) — see upstream LICENSE"
  echo
  (cd "$DEST" && shasum -a 256 *.c *.h)
} > "$DEST/VENDOR"

echo "vendored libmizu @ $REF ($commit) into $DEST"
